app:
  name: "web_app"
  mode: "dev"
  port: 8081
  version: "v0.1.4"
  start_time: "2020-07-01 15:04:05"
  machine_id: 1


log:
  level:  "debug"
  filename:  "web_app.log"
  max_size:  200
  max_age:  30
  max_backups:  7
mysql:
  host:  "127.0.0.1"
  port:   3306
  user:  "root"
  password:  "123456"
  dbname:  "sql_demo"
  max_open_connes:  200
  max_idle_connes:    50

redis:
  host: "127.0.0.1"
  port: 6379
  db: 0
  password: ""
  pool_size: 100
